title: Products
template: products.jinja

products:
  - ld-cabb
  - ldb-add0812
  - ldb-bi16
  - ldb-es05100
  - ldb-icl9024
  - ldb-ips0405
  - ldb-psd05
  - ldb-pst05
  - ldb-ucu1294

scripts:
  products: products/products.py
